export const authConstant = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  IS_ALDREADY_LOGIN_REQUEST: "IS_ALDREADY_LOGIN_REQUEST",
  IS_ALDREADY_LOGIN_SUCCESS: "IS_ALDREADY_LOGIN_SUCCESS",
  IS_ALDREADY_LOGIN_FAILURE: "IS_ALDREADY_LOGIN_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  AUTH_AXIOS_ERROR: "AUTH_AXIOS_ERROR",
};

export const shopConstant = {
  CREATE_SHOP_REQUEST: "CREATE_SHOP_REQUEST",
  CREATE_SHOP_SUCCESS: "CREATE_SHOP_SUCCESS",
  CREATE_SHOP_FAILURE: "CREATE_SHOP_FAILURE",
  CREATE_SHOP_AXIOS_ERROR: "CREATE_SHOP_AXIOS_ERROR",

  GET_SHOP_REQUEST: "GET_SHOP_REQUEST",
  GET_SHOP_FAILURE: "GET_SHOP_FAILURE",
  GET_SHOP_SUCCESS: "GET_SHOP_SUCCESS",
  GET_SHOP_AXIOS_ERROR: "GET_SHOP_AXIOS_ERROR",

  REFRESH_SHOP_REQUEST: "REFRESH_SHOP_REQUEST",
  REFRESH_SHOP_FAILURE: "REFRESH_SHOP_FAILURE",
  REFRESH_SHOP_SUCCESS: "REFRESH_SHOP_SUCCESS",
};

export const productConstant = {
  CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAILURE: "CREATE_PRODUCT_FAILURE",
  CREATE_PRODUCT_AXIOS_ERROR: "CREATE_PRODUCT_AXIOS_ERROR",

  GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_FAILURE: "GET_ALL_PRODUCT_FAILURE",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_AXIOS_ERROR: "GET_ALL_PRODUCT_AXIOS_ERROR",

  REFRESH_REQUEST: "REFRESH_REQUEST",
  REFRESH_FAILURE: "REFRESH_FAILURE",
  REFRESH_SUCCESS: "REFRESH_SUCCESS",
};

export const orderConstant = {
  CREATE_ORDER_REQUEST: "CREATE_ORDER_REQUEST",
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  CREATE_ORDER_FAILURE: "CREATE_ORDER_FAILURE",
  CREATE_ORDER_AXIOS_ERROR: "CREATE_ORDER_AXIOS_ERROR",

  GET_ORDER_REQUEST: "GET_ORDER_REQUEST",
  GET_ORDER_FAILURE: "GET_ORDER_FAILURE",
  GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
  GET_ORDER_AXIOS_ERROR: "GET_ORDER_AXIOS_ERROR",

  REFRESH_ORDER_REQUEST: "REFRESH_ORDER_REQUEST",
  REFRESH_ORDER_FAILURE: "REFRESH_ORDER_FAILURE",
  REFRESH_ORDER_SUCCESS: "REFRESH_ORDER_SUCCESS",
};
